
import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'hi' | 'mr';

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    welcome: "Welcome",
    enterApp: "Enter UniShare",
    marketplace: "Marketplace",
    notesHub: "Notes Hub",
    scanner: "Scanner",
    profile: "Profile",
    safeZones: "Safe Zones",
    karma: "Karma",
    varasa: "Legacy",
    searchPlaceholder: "Search for kits, sensors, or notes...",
    recentSearches: "Recent Searches",
    popularCategories: "Popular Categories",
    logout: "Logout",
    loginEmail: "University Email",
    loginError: "Please use your @bvuniversity.edu.in email",
    loading: "Authenticating...",
    aiAuditLoading: "AI is performing an honest audit of your gear... identifying faults...",
    tradeCenter: "Trade Center",
    exchangeDesc: "Exchange kits, sensors & project hardware",
    category: "Category",
    deptYear: "Department / Year",
    sold: "Sold",
    chat: "Chat",
    summarize: "Quick Summary",
    upload: "Upload Resources",
    scanTitle: "AI Tool Audit",
    scanDesc: "Verified grading for engineering hardware",
    openCamera: "Open Camera",
    safetyTip: "Safety Tip",
    safetyDesc: "Always meet at verified Safe Zones like the Central Library.",
    wishlist: "Wishlist",
    compare: "Compare",
    comparison: "Item Comparison",
    condition: "Condition",
    carbon: "Carbon Saved",
    selectToCompare: "Select 2 items to compare",
    noWishlist: "Your wishlist is empty.",
    backToAll: "Back to All Items",
    request: "Request",
    requested: "Requested",
    cancelRequest: "Cancel Request",
    accept: "Accept",
    accepted: "Accepted",
    verifiedStudent: "Verified Student",
    helpSafety: "Help & Safety",
    reportFake: "Report Fake Content",
    contactSupport: "Contact Support",
    faq: "FAQs",
    cancel: "Cancel",
    cancelled: "Cancelled",
    reportSuccess: "Item reported. Thank you for keeping UniShare safe.",
    supportBot: "Support Assistant",
    typeMessage: "Type your query...",
    close: "Close",
    safetyHandshake: "Safety Handshake",
    scanToComplete: "Scan QR to Complete Trade",
    verifyLocation: "Verify Location at Library",
    addListing: "Add New Listing",
    itemName: "Item Name",
    description: "Description",
    price: "Price (₹)",
    department: "Department",
    submitListing: "Submit Listing",
    listingSuccess: "Listing created successfully!",
    shareMaterial: "Share Material",
    materialTitle: "Document Title",
    subject: "Subject / Course",
    semester: "Semester",
    materialType: "Material Type",
    uploadSuccess: "Material shared successfully!",
    hardcopy: "Hardcopy (Handwritten)",
    softcopy: "PDF (Softcopy)",
    download: "Download",
    requestTrade: "Request Trade",
    tradeRequestSent: "Request sent! Meet the seller at the Central Library safe zone once they Accept.",
    shareApp: "Invite Friends",
    shareItem: "Share Deal",
    appShareText: "Check out UniShare - The exclusive marketplace for BVDUCOEP students!",
    itemShareText: "Found a great deal on UniShare: ",
    linkCopied: "Link copied to clipboard!"
  },
  hi: {
    welcome: "स्वागत है",
    enterApp: "प्रवेश करें",
    marketplace: "मार्केटप्लेस",
    notesHub: "नोट्स हब",
    scanner: "स्कैनर",
    profile: "प्रोफ़ाइल",
    safeZones: "सुरक्षित क्षेत्र",
    karma: "कर्मा",
    varasa: "विरासत",
    searchPlaceholder: "किट, सेंसर या नोट्स खोजें...",
    recentSearches: "हाल की खोजें",
    popularCategories: "लोकप्रिय श्रेणियां",
    logout: "लॉगआउट",
    loginEmail: "विश्वविद्यालय ईमेल",
    loginError: "कृपया अपना @bvuniversity.edu.in ईमेल उपयोग करें",
    loading: "प्रमाणित किया जा रहा है...",
    aiAuditLoading: "एआई आपके गियर का ईमानदारी से ऑडिट कर रहा है... दोषों की पहचान कर रहा है...",
    tradeCenter: "ट्रेड सेंटर",
    exchangeDesc: "किट, सेंसर और प्रोजेक्ट हार्डवेयर का आदान-प्रदान",
    category: "श्रेणी",
    deptYear: "विभाग / वर्ष",
    sold: "बिक गया",
    chat: "चैट",
    summarize: "त्वरित सारांश",
    upload: "संसाधन अपलोड करें",
    scanTitle: "AI टूल ऑडिट",
    scanDesc: "इंजीनियरिंग हार्डवेयर के लिए सत्यापित ग्रेडिंग",
    openCamera: "कैमरा खोलें",
    safetyTip: "सुरक्षा सुझाव",
    safetyDesc: "हमेशा सेंट्रल लाइब्रेरी जैसे सत्यापित सुरक्षित क्षेत्रों में मिलें।",
    wishlist: "विशलिस्ट",
    compare: "तुलना करें",
    comparison: "वस्तु तुलना",
    condition: "स्थिति",
    carbon: "बचाया गया कार्बन",
    selectToCompare: "तुलना के लिए 2 वस्तुएं चुनें",
    noWishlist: "आपकी विशलिस्ट खाली है।",
    backToAll: "सभी वस्तुओं पर वापस जाएं",
    request: "अनुरोध",
    requested: "अनुरोधित",
    cancelRequest: "अनुरोध रद्द करें",
    accept: "स्वीकार करें",
    accepted: "स्वीकृत",
    verifiedStudent: "सत्यापित छात्र",
    helpSafety: "सहायता और सुरक्षा",
    reportFake: "फर्जी सामग्री की रिपोर्ट करें",
    contactSupport: "सपोर्ट से संपर्क करें",
    faq: "सामान्य प्रश्न",
    cancel: "रद्द करें",
    cancelled: "रद्द किया गया",
    reportSuccess: "सामग्री की रिपोर्ट कर दी गई है। सुरक्षित रहने में मदद के लिए धन्यवाद।",
    supportBot: "Support Assistant",
    typeMessage: "अपना प्रश्न लिखें...",
    close: "बंद करें",
    safetyHandshake: "सुरक्षा हैंडशेक",
    scanToComplete: "व्यापार पूरा करने के लिए QR स्कैन करें",
    verifyLocation: "लाइब्रेरी में स्थान सत्यापित करें",
    addListing: "नई लिस्टिंग जोड़ें",
    itemName: "वस्तु का नाम",
    description: "विवरण",
    price: "कीमत (₹)",
    department: "विभाग",
    submitListing: "लिस्टिंग जमा करें",
    listingSuccess: "लिस्टिंग सफलतापूर्वक बनाई गई!",
    shareMaterial: "साहित्य साझा करें",
    materialTitle: "दस्तावेज़ का शीर्षक",
    subject: "विषय / कोर्स",
    semester: "सेमेस्टर",
    materialType: "साहित्य का प्रकार",
    uploadSuccess: "साहित्य सफलतापूर्वक साझा किया गया!",
    hardcopy: "हार्डकॉपी (हस्तलिखित)",
    softcopy: "PDF (सॉफ्टकॉपी)",
    download: "डाउनलोड करें",
    requestTrade: "ट्रेड का अनुरोध करें",
    tradeRequestSent: "अनुरोध भेज दिया गया! उनके स्वीकार करने के बाद सेंट्रल लाइब्रेरी सुरक्षित क्षेत्र में मिलें।",
    shareApp: "मित्रों को आमंत्रित करें",
    shareItem: "डील साझा करें",
    appShareText: "UniShare देखें - BVDUCOEP छात्रों के लिए विशेष मार्केटप्लेस!",
    itemShareText: "UniShare पर एक शानदार डील मिली: ",
    linkCopied: "लिंक क्लिपबोर्ड पर कॉपी किया गया!"
  },
  mr: {
    welcome: "स्वागत आहे",
    enterApp: "प्रवेश करा",
    marketplace: "मार्केटप्लेस",
    notesHub: "नोट्स हब",
    स्कॅनर: "स्कॅनर",
    profile: "प्रोफाइल",
    safeZones: "सुरक्षित क्षेत्र",
    karma: "कर्मा",
    varasa: "वारसा",
    searchPlaceholder: "किट, सेन्सर किंवा नोट्स शोधा...",
    recentSearches: "अलीकडील शोध",
    popularCategories: "लोकप्रिय श्रेणी",
    logout: "बाहेर पडा",
    loginEmail: "विद्यापीठ ईमेल",
    loginError: "कृपया तुमचा @bvuniversity.edu.in ईमेल वापरा",
    loading: "प्रमाणित करत आहे...",
    aiAuditLoading: "AI तुमच्या उपकरणाचे प्रामाणिक ऑडिट करत आहे... दोष शोधत आहे...",
    tradeCenter: "ट्रेड सेंटर",
    exchangeDesc: "किट, सेन्सर आणि प्रोजेक्ट हार्डवेअरची देवाणघेवाण",
    category: "श्रेणी",
    deptYear: "विभाग / वर्ष",
    sold: "विकले गेले",
    chat: "चॅट",
    summarize: "त्वरित सारांश",
    upload: "संसाधन अपलोड करा",
    scanTitle: "AI टूल ऑडिट",
    scanDesc: "इंजिनिअरिंग हार्डवेअरसाठी सत्यापित ग्रेडिंग",
    openCamera: "कैमरा खोलें",
    safetyTip: "सुरक्षा टीप",
    safetyDesc: "नेहमी सेंट्रल लायब्ररीसारख्या सत्यापित सुरक्षित क्षेत्रांमध्ये भेटा.",
    wishlist: "विशलिस्ट",
    compare: "तुलना करा",
    comparison: "वस्तू तुलना",
    condition: "स्थिती",
    carbon: "वाचवलेला कार्बन",
    selectToCompare: "तुलनेसाठी २ वस्तू निवडा",
    noWishlist: "तुमची विशलिस्ट रिकामी आहे.",
    backToAll: "सर्व वस्तूंवर परत जा",
    request: "विनंती",
    requested: "विनंती केली",
    cancelRequest: "विनंती रद्द करा",
    accept: "स्वीकारा",
    accepted: "स्वीकारले",
    verifiedStudent: "सत्यापित विद्यार्थी",
    helpSafety: "मदत आणि सुरक्षा",
    reportFake: "चुकीच्या माहितीची तक्रार करा",
    contactSupport: "सपोर्टशी संपर्क साधा",
    faq: "वारंवार विचारले जाणारे प्रश्न",
    cancel: "रद्द करा",
    cancelled: "रद्द केले",
    reportSuccess: "तक्रार नोंदवण्यात आली आहे. युनिशेअर सुरक्षित ठेवण्यास मदत केल्याबद्दल धन्यवाद.",
    supportBot: "Support Assistant",
    typeMessage: "तुमचा प्रश्न टाइप करा...",
    close: "बंद करा",
    safetyHandshake: "सुरक्षा हँडशेक",
    scanToComplete: "व्यवहार पूर्ण करण्यासाठी QR स्कॅन करा",
    verifyLocation: "लायब्ररीमध्ये स्थान सत्यापित करा",
    addListing: "नवीन लिस्टिंग जोडा",
    itemName: "वस्तूचे नाव",
    description: "वर्णन",
    price: "किंमत (₹)",
    department: "विभाग",
    submitListing: "लिस्टिंग सबमिट करा",
    listingSuccess: "लिस्टिंग यशस्वीरित्या तयार झाली!",
    shareMaterial: "साहित्य शेअर करा",
    materialTitle: "साहित्याचे नाव",
    subject: "विषय / कोर्स",
    semester: "सेमिस्टर",
    materialType: "साहित्याचा प्रकार",
    uploadSuccess: "साहित्य यशस्वीरित्या शेअर झाले!",
    hardcopy: "हार्डकॉपी (हस्तलिखित)",
    softcopy: "PDF (सॉफ्टकॉपी)",
    download: "डाउनलोड करा",
    requestTrade: "ट्रेडची विनंती करा",
    tradeRequestSent: "विनंती पाठवली! त्यांनी स्वीकारल्यावर सेंट्रल लायब्ररी सुरक्षित क्षेत्रात भेटा.",
    shareApp: "मित्रांना आमंत्रित करा",
    shareItem: "डील शेअर करा",
    appShareText: "UniShare पहा - BVDUCOEP विद्यार्थ्यांसाठी विशेष मार्केटप्लेस!",
    itemShareText: "UniShare वर एक उत्तम डील सापडली: ",
    linkCopied: "लिंक क्लिपबोर्डवर कॉपी केली!"
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [lang, setLangState] = useState<Language>(() => {
    return (localStorage.getItem('app_lang') as Language) || 'en';
  });

  const setLang = (newLang: Language) => {
    setLangState(newLang);
    localStorage.setItem('app_lang', newLang);
  };

  const t = (key: string) => {
    return translations[lang][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};
